﻿namespace LlamaLibrary.Enums
{
    public enum MyItemRole : byte
    {
        None = 0,
        PhysicalWeapon = 1,
        MagicalWeapon = 2,
        Shield = 3,
        Armor = 4,
        Food = 5,
        StatPotion = 6,
        SpecialPotion_Manual = 7,
        HealingPotion = 8,
        Ether = 9,
        Elixir = 10,
        Crystals = 11,
        CraftingMaterial = 12,
        Materia = 13,
        Housing = 14,
        Dye = 15,
        General = 16,
        Bait = 17,
        Map = 18,
        Container = 19,
        Seed = 20,
        Soil = 21,
        Fertilizer = 22,
        CraftingTome = 23,
        Unknown = 24,
        BlankAetherialWheel = 25,
        PrimedAetherialWheel = 26,
        TripleTriadCard = 27,
        AirshipPart = 28,
        SpecialCurrency = 29,
        FolkloreTome = 30,
        Favor = 31,
        SoulCrystal = 32,
        OrchestrionRoll = 33,
        AquariumTrimming = 34,
        Painting = 35,
        RetainerBoost = 36,
        SubmersiblePart = 37,
        EurekaLogogram = 38
    }
}