//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LlamaLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LlamaLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:{&quot;BNpcNameKey&quot;:785,&quot;Location&quot;:{&quot;X&quot;:-279.682159,&quot;Y&quot;:256.4128,&quot;Z&quot;:339.207031,&quot;MagnitudeSqr&quot;:259031.047,&quot;Magnitude&quot;:508.950928},&quot;Map&quot;:155},&quot;2&quot;:{&quot;BNpcNameKey&quot;:1809,&quot;Location&quot;:{&quot;X&quot;:-425.2555,&quot;Y&quot;:-15.8549,&quot;Z&quot;:-426.810364,&quot;MagnitudeSqr&quot;:363260.7,&quot;Magnitude&quot;:602.7111},&quot;Map&quot;:156},&quot;3&quot;:{&quot;BNpcNameKey&quot;:1829,&quot;Location&quot;:{&quot;X&quot;:-292.6528,&quot;Y&quot;:-41.6489868,&quot;Z&quot;:-327.657,&quot;MagnitudeSqr&quot;:194739.422,&quot;Magnitude&quot;:441.2929},&quot;Map&quot;:138},&quot;4&quot;:{&quot;BNpcNameKey&quot;:869,&quot;Location&quot;:{&quot;X&quot;:-356.110168,&quot;Y&quot;:14.98069,&quot;Z&quot;:-737.064331,&quot;MagnitudeSqr&quot;:67 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllHunts {
            get {
                return ResourceManager.GetString("AllHunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:[{&quot;Key&quot;:5724,&quot;Tier&quot;:0,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;&quot;},{&quot;Key&quot;:5725,&quot;Tier&quot;:1,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;&quot;},{&quot;Key&quot;:5726,&quot;Tier&quot;:2,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;&quot;},{&quot;Key&quot;:5727,&quot;Tier&quot;:3,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;&quot;}],&quot;2&quot;:[{&quot;Key&quot;:5604,&quot;Tier&quot;:0,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;},{&quot;Key&quot;:5605,&quot;Tier&quot;:1,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;},{&quot;Key&quot;:5606,&quot;Tier&quot;:2,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;},{&quot;Key&quot;:5607,&quot;Tier&quot;:3,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;},{&quot;Key&quot;:5608,&quot;Tier&quot;:4,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;},{&quot;Key&quot;:18006,&quot;Tier&quot;:5,&quot;Value&quot;:0,&quot;Stat&quot;:&quot;Strength&quot;}],&quot;3&quot;:[{&qu....
        /// </summary>
        internal static string Materia {
            get {
                return ResourceManager.GetString("Materia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: 1,
        ///    &quot;ClassJobCategory&quot;: 34,
        ///    &quot;IsRandom&quot;: false,
        ///    &quot;RetainerLevel&quot;: 1,
        ///    &quot;VentureCost&quot;: 1,
        ///    &quot;MaxTime&quot;: 60,
        ///    &quot;Experience&quot;: 1300,
        ///    &quot;RequiredItemLevel&quot;: 0,
        ///    &quot;RequiredGathering&quot;: 0,
        ///    &quot;NameRaw&quot;: &quot;Animal Skin&quot;,
        ///    &quot;ItemId&quot;: 5291
        ///  },
        ///  {
        ///    &quot;Id&quot;: 2,
        ///    &quot;ClassJobCategory&quot;: 34,
        ///    &quot;IsRandom&quot;: false,
        ///    &quot;RetainerLevel&quot;: 2,
        ///    &quot;VentureCost&quot;: 1,
        ///    &quot;MaxTime&quot;: 60,
        ///    &quot;Experience&quot;: 1900,
        ///    &quot;RequiredItemLevel&quot;: 0,
        ///    &quot;RequiredGathering&quot;: 0,
        ///    &quot;N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ventures {
            get {
                return ResourceManager.GetString("Ventures", resourceCulture);
            }
        }
    }
}
