//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LlamaLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LlamaLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;1&quot;:[{&quot;Key&quot;:5724,&quot;Tier&quot;:0,&quot;Value&quot;:0},{&quot;Key&quot;:5725,&quot;Tier&quot;:1,&quot;Value&quot;:0},{&quot;Key&quot;:5726,&quot;Tier&quot;:2,&quot;Value&quot;:0},{&quot;Key&quot;:5727,&quot;Tier&quot;:3,&quot;Value&quot;:0}],&quot;2&quot;:[{&quot;Key&quot;:5604,&quot;Tier&quot;:0,&quot;Value&quot;:0},{&quot;Key&quot;:5605,&quot;Tier&quot;:1,&quot;Value&quot;:0},{&quot;Key&quot;:5606,&quot;Tier&quot;:2,&quot;Value&quot;:0},{&quot;Key&quot;:5607,&quot;Tier&quot;:3,&quot;Value&quot;:0},{&quot;Key&quot;:5608,&quot;Tier&quot;:4,&quot;Value&quot;:0},{&quot;Key&quot;:18006,&quot;Tier&quot;:5,&quot;Value&quot;:0}],&quot;3&quot;:[{&quot;Key&quot;:5609,&quot;Tier&quot;:0,&quot;Value&quot;:0},{&quot;Key&quot;:5610,&quot;Tier&quot;:1,&quot;Value&quot;:0},{&quot;Key&quot;:5611,&quot;Tier&quot;:2,&quot;Value&quot;:0},{&quot;Key&quot;:5612,&quot;Tier&quot;:3,&quot;Value&quot;:0},{&quot;Key&quot;:5613,&quot;Tier&quot;:4,&quot;Value&quot;:0},{&quot;Key&quot;:18007, [rest of string wa....
        /// </summary>
        internal static string Materia {
            get {
                return ResourceManager.GetString("Materia", resourceCulture);
            }
        }
    }
}
